dist: bionic
language: python
python: 2.7
services:
- docker
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install python3 python3-pip gcc git make -y

install:
- pip install -r requirements.txt
- pip install -e git+https://github.com/USGS-EROS/espa-python-library.git@v1.1.0#egg=espa

script: nose2

after_success:
- "./bin/build"
