# File: main.yml
# Description: Default values for espa-worker role

app_user: espa
app_group: ie
user_group: users
processing_tagname: topic/espa-worker

espa_release: 2.35.0
espa_aux: 2.34.0
gdal_espa: 1.11.1
proj_espa: 4.8.0