# File: espa-software.yml
# Description: Install ESPA software and system package dependencies
# Last Updated: See 'git log -p <filename>'
# Recent Changes: See 'git log -p <filename>'

# ---- ESPA/LSRD CUSTOM REPOS ---- #

# Install LSRD Repo
- name: espa-software|Add LSRD Custom Repo
  yum_repository:
    name: lsrd
    description: LSRD - System Package Repository
    file: lsrd
    baseurl: http://lsrdrepo.cr.usgs.gov/repo/lsrd/el6/
    gpgcheck: no
    enabled: yes
    metadata_expire: 300

# Install ESPA Repo
- name: espa-software|Add ESPA Custom Repo
  yum_repository:
    name: espa
    description: ESPA - Package Repository
    file: lsrd
    baseurl: http://lsrdrepo.cr.usgs.gov/repo/espa/el6/
    gpgcheck: no
    enabled: yes
    metadata_expire: 300


# ---- ESPA PYTHON LIBRARY ---- #

# Install espa-python library
- name: espa-software|Install espa-python-library
  pip:
    editable: false
    version: 1.1.0
    name: "git+https://github.com/USGS-EROS/espa-python-library.git@v1.1.0#egg=espa"


# ---------- ESPA SOFTWARE RELEASE GROUP ---------- #
# (software versions defined in external vars file) #
# ------------------------------------------------- #


# Install modtran-espa
- name: espa-software|Install modtran-espa
  yum:
    name: "modtran-espa-{{ modtran_espa }}"
    state: installed

# Build and install espa-product-formatter
- name: espa-software|Build espa-product-formatter
  make:
    chdir: /src/espa-product-formatter
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes

- name: espa-software|Install espa-product-formatter
  make:
    chdir: /src/espa-product-formatter
    params:
      PREFIX: /usr/local
    target: install

- name: espa-software|Clean espa-product-formatter
  file:
    path: /src/espa-product-formatter
    state: absent


## Install espa-l2qa-tools
- name: espa-software|Build espa-l2qa-tools
  make:
    chdir: /src/espa-l2qa-tools
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes

- name: espa-software|Install espa-l2qa-tools
  make:
    chdir: /src/espa-l2qa-tools
    params:
      PREFIX: /usr/local
    target: install

- name: espa-software|Clean espa-l2qa-tools
  file:
    path: /src/espa-l2qa-tools
    state: absent


## Install espa-aquatic-reflectance
- name: espa-software|Copy lib3 from espa-aq-refl
  command:
    cmd: cp -r /src/espa-aq-refl/src/lib3 /usr/local/

- name: espa-software|Build espa-aq-refl
  make:
    chdir: /src/espa-aq-refl
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes

- name: espa-software|Install espa-aq-refl
  make:
    chdir: /src/espa-aq-refl
    params:
      PREFIX=/usr/local
    target: install

- name: espa-software|Clean espa-aq-refl
  file:
    path: /src/espa-aq-refl
    state: absent


## Install espa-surface-reflectance
- name: espa-software|Build all espa-surface-reflectance
  make:
    chdir: /src/espa-surface-reflectance
    target: all-script

- name: espa-software|Install espa-surface-reflectance
  make:
    chdir: /src/espa-surface-reflectance
    params:
      PREFIX: /usr/local
    target: install-script

- name: espa-software|Clean espa-surface-reflectance
  file:
    path: /src/espa-surface-reflectance
    state: absent


## Install espa-surface-reflectance-ledaps
- name: espa-software|Build espa-surface-reflectance-ledaps
  make:
    chdir: /src/espa-surface-reflectance-ledaps
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes
    target: all-ledaps

- name: espa-software|Install espa-surface-reflectance-ledaps
  make:
    chdir: /src/espa-surface-reflectance-ledaps
    params:
      PREFIX=/usr/local
    target: install-ledaps

- name: espa-software|Clean espa-surface-reflectance-ledaps
  file:
    path: /src/espa-surface-reflectance-ledaps
    state: absent


## Install espa-surface-reflectance-lasrc
- name: espa-software|Build espa-surface-reflectance-lasrc
  make:
    chdir: /src/espa-surface-reflectance-lasrc
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes
    target: all-lasrc

- name: espa-software|Install espa-surface-reflectance-lasrc
  make:
    chdir: /src/espa-surface-reflectance-lasrc
    params:
      PREFIX: /usr/local
    target: install-lasrc

- name: espa-software|Clean espa-surface-reflectance-lasrc
  file:
    path: /src/espa-surface-reflectance-lasrc
    state: absent


## Install espa-surface-temperature
- name: espa-software|Build espa-surface-temperature
  make:
    chdir: /src/espa-surface-temperature
    params:
      BUILD_STATIC: yes
    target: all-script

- name: espa-software|Install espa-surface-temperature
  make:
    chdir: /src/espa-surface-temperature
    params:
      PREFIX: /usr/local
    target: install-script

- name: espa-software|Clean espa-surface-temperature
  file:
    path: /src/espa-surface-temperature
    state: absent


## Install espa-surface-temperature-rit
- name: espa-software|Build espa-surface-temperature-rit
  make:
    chdir: /src/espa-surface-temperature-rit
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes
    target: all-rit

- name: espa-software|Install espa-surface-temperature-rit
  make:
    chdir: /src/espa-surface-temperature-rit
    params:
      PREFIX: /usr/local
    target: install-rit

- name: espa-software|Clean espa-surface-temperature-rit
  file:
    path: /src/espa-surface-temperature-rit
    state: absent


## Install espa-spectral-indices
- name: espa-software|Build espa-spectral-indices
  make:
    chdir: /src/espa-spectral-indices
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes

- name: espa-software|Install espa-spectral-indices
  make:
    chdir: /src/espa-spectral-indices
    params:
      PREFIX: /usr/local
    target: install

- name: espa-software|Clean espa-spectral-indices
  file:
    path: /src/espa-spectral-indices
    state: absent


## Install espa-surface-water-extent
- name: espa-software|Build espa-surface-water-extent
  make:
    chdir: /src/espa-surface-water-extent
    target: all-script

- name: espa-software|Install espa-surface-water-extent
  make:
    chdir: /src/espa-surface-water-extent
    params:
      PREFIX: /usr/local
    target: install-script

- name: espa-software|Clean espa-surface-water-extent
  file:
    path: /src/espa-surface-water-extent
    state: absent


## Install espa-surface-water-extent-cfbwd
- name: espa-software|Build espa-surface-water-extent-cfbwd
  make:
    chdir: /src/espa-surface-water-extent-cfbwd
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes
    target: all-cfbwd

- name: espa-software|Install espa-surface-water-extent-cfbwd
  make:
    chdir: /src/espa-surface-water-extent-cfbwd
    params:
      PREFIX: /usr/local
    target: install-cfbwd

- name: espa-software|Clean espa-surface-water-extent-cfbwd
  file:
    path: /src/espa-surface-water-extent-cfbwd
    state: absent


## Install espa-surface-water-extent-dswe
- name: espa-software|Build espa-surface-water-extent-dswe
  make:
    chdir: /src/espa-surface-water-extent-dswe
    params:
      BUILD_STATIC: yes
      ENABLE_THREADING: yes
    target: all-dswe

- name: espa-software|Install espa-surface-water-extent-dswe
  make:
    chdir: /src/espa-surface-water-extent-dswe
    params:
      PREFIX: /usr/local
    target: install-dswe

- name: espa-software|Clean espa-surface-water-extent-dswe
  file:
    path: /src/espa-surface-water-extent-dswe
    state: absent


## Install espa-elevation
- name: espa-software|Build espa-elevation
  make:
    chdir: /src/espa-elevation

- name: espa-software|Install espa-elevation
  make:
    chdir: /src/espa-elevation
    params:
      PREFIX: /usr/local
    target: install

- name: espa-software|Clean espa-elevation
  file:
    path: /src/espa-elevation
    state: absent


## Install espa-reprojection
- name: espa-software|Build espa-reprojection
  make:
    chdir: /src/espa-reprojection

- name: espa-software|Install espa-reprojection
  make:
    chdir: /src/espa-reprojection
    params:
      PREFIX: /usr/local
    target: install

- name: espa-software|Clean espa-reprojection
  file:
    path: /src/espa-reprojection
    state: absent


## Install espa-plotting
- name: espa-software|Build espa-plotting
  make:
    chdir: /src/espa-plotting

- name: espa-software|Install espa-plotting
  make:
    chdir: /src/espa-plotting
    params:
      PREFIX: /usr/local
    target: install

- name: espa-software|Clean espa-plotting
  file:
    path: /src/espa-plotting
    state: absent


## Link to the opj2_decompress executable
- name: espa-software|Link opj2_decompress to opj_decompress
  file:
    src: "/usr/bin/opj2_decompress"
    dest: "/usr/bin/opj_decompress"
    state: link



