# File: espa-software.yml
# Description: Install ESPA software and system package dependencies
# Last Updated: See 'git log -p <filename>'
# Recent Changes: See 'git log -p <filename>'

# Install LSRD Repo
- name: espa-software|Add LSRD Custom Repo
  yum_repository:
    name: lsrd
    description: LSRD - System Package Repository
    file: lsrd
    baseurl: http://lsrdrepo.cr.usgs.gov/repo/lsrd/el6/
    gpgcheck: no
    enabled: yes
    metadata_expire: 300

# Install ESPA Repo
- name: espa-software|Add ESPA Custom Repo
  yum_repository:
    name: espa
    description: ESPA - Package Repository
    file: lsrd
    baseurl: http://lsrdrepo.cr.usgs.gov/repo/espa/el6/
    gpgcheck: no
    enabled: yes
    metadata_expire: 300

# Install espa-release group
- name: espa-software|Install espa-release group
  yum:
    name: "@espa-release"
    state: installed

# Install espa-python library
- name: espa-software|Install espa-python-library
  pip:
    executable: "/usr/local/bin/pip"
    editable: false
    version: 1.1.0
    name: "git+https://github.com/USGS-EROS/espa-python-library.git@v1.1.0#egg=espa"
