# File: main.yml
# Description: Main task file for role 'espa-worker'
# Last Updated: See 'git log -p <filename>'
# Recent Changes: See 'git log -p <filename>'

# Add user and group
- import_tasks: user-group.yml
  tags: user-group, configuration

# Setup mounts
- import_tasks: mounts.yml
  tags: mounts, configuration

# Install ESPA Software
- import_tasks: espa-software.yml
  tags: packages

# Install Worker Dependencies
- import_tasks: worker-dependencies.yml
  tags: dependencies

# Directories and Symlinks
- import_tasks: dirs-links.yml
  tags: dirs-links, configuration
