# File: mounts.yml
# Description: Setup espa worker mount points
# Last Updated: See 'git log -p <filename>'
# Recent Changes: See 'git log -p <filename>'

- name: mounts|Create ESPA Storage Directory
  file:
    path: "/espa-storage"
    state: directory
    owner: root
    mode: 0755

- name: mounts|Create ESPA Storage Orders Mount Point
  file:
    path: "/espa-storage/orders"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0775

- name: mounts|Create Data Staging Area
  file:
    path: "/data/staging"
    state: directory
    owner: root
    mode: 0777

- name: mounts|Create Data Working Area
  file:
      path: "/data/working"
      state: directory
      owner: root
      mode: 0777

- name: mounts|Create Output Data Mount Point
  file:
    path: "/data/output"
    state: directory
    owner: root
    mode: 0777

- name: mounts|Create Auxiliaries Mount Point
  file:
    path: "/usr/local/auxiliaries"
    state: directory
    owner: root
    mode: 0755
