# File: mounts.yml
# Description: Setup espa worker mount points
# Last Updated: See 'git log -p <filename>'
# Recent Changes: See 'git log -p <filename>'

- name: mounts|Create Auxiliaries Mount Point
  file:
    path: "/usr/local/auxiliaries"
    state: directory
    owner: root
    mode: 0755
