# File: mounts.yml
# Description: Setup lsrd hadoop mount points
# Last Updated: See 'git log -p <filename>'
# Recent Changes: See 'git log -p <filename>'

- name: mounts|Create Scratch Workspace
  file:
    path: "/data"
    state: directory
    owner: root
    mode: 0775

- name: mounts|Create Auxiliaries Mount Point
  file:
    path: "/usr/local/auxiliaries"
    state: directory
    owner: root
    mode: 0755

- name: mounts|Create ESPA Storage Directory
  file:
    path: "/espa-storage"
    state: directory
    owner: root
    mode: 0755

- name: mounts|Create ESPA Storage Orders Mount Point
  file:
    path: "/espa-storage/orders"
    state: directory
    owner: root
    mode: 0775
